### ISSUE TITLE
Cannot compile bigquery-storage as it depends on a broken packed_simd

### ISSUE THREAD

**Issue by OPeyrusse** [openquery-io/bigquery-storage#1]
Through the late arrow dependency, this crate depends on _packed_simd_ which is currently in a broken state [1].
This dependency is coming from _arrow_ which updated to 3.0.0 - latest at the current time.
Although the diff [2] show only one changed file for rust with a minor change, I did not manage to force this version as this crate enforces "arrow ^0.16.0".

Would you consider upgrading? I can provide a PR for this, but without a contribution guide, I am not sure of what I am supposed to do.

[1] https://github.com/rust-lang/packed_simd
[2] https://github.com/apache/arrow/compare/master...maint-0.17.x#diff-d6de2aa116b82bf7bfdf40fcbad13dc947139ce7a703990517662ae25eab0159

**Comment by brokad** [comment]
Thanks for noticing! Of course. I haven't had time to allocate to this crate in a little while. #2 should address this.

**Comment by OPeyrusse** [comment]
Many thanks @brokad for the very quick action. I would have help but I wasn't sure if you had any tests.
And thanks for this change [1] to the example snippet. I was briefly wondering what to do with the NoneError value :smile: 

[1] https://github.com/openquery-io/bigquery-storage/pull/2/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by OPeyrusse** [comment]
By any chance, would you consider issuing a release with the fix ? I know how to pull the version from master, but that would be a nice-have.
